# Generated by Django 5.2.7 on 2025-11-17 02:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, help_text='Ej: HRFRZ, RIUE, SAR', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad de Salud',
                'verbose_name_plural': 'Unidades de Salud',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='antecedentes',
            field=models.TextField(blank=True, verbose_name='Antecedentes'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='estado',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('recibida', 'Recibida'), ('aceptada', 'Aceptada')], default='enviada', max_length=20),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Frec. Cardíaca (lpm)'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Frec. Respiratoria (rpm)'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='gravedad',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=10),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='nivel_conciencia',
            field=models.CharField(blank=True, choices=[('alerta', 'Alerta'), ('verbal', 'Responde a voz'), ('dolor', 'Responde a dolor'), ('inconsciente', 'Inconsciente')], max_length=20, verbose_name='Nivel de conciencia (AVPU)'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=20, verbose_name='Presión Arterial'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='rut_paciente',
            field=models.CharField(blank=True, help_text='Ej: 12.345.678-9', max_length=12, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(45)], verbose_name='Temperatura (°C)'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('paramedico', 'Paramédico'), ('tens', 'TENS'), ('enfermero', 'Enfermero/a'), ('medico', 'Médico/Doctor'), ('coordinador', 'Coordinador Telered/Unidad'), ('ambulancia', 'Personal Ambulancia RIU/SAR'), ('admin_red', 'Administrador Red/SSO')], default='paramedico', max_length=20),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='apellido_paciente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='nombre_paciente',
            field=models.CharField(default='NN', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='unidad_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamnesis_recibidas', to='pagina.unidad'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina.unidad'),
        ),
    ]
