# Generated by Django 5.2.7 on 2025-11-17 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_unidad_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='especialidad',
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='FC (lpm)'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='FR (rpm)'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=20, verbose_name='PA'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='rut_paciente',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='codigo',
            field=models.CharField(blank=True, help_text='Ej: HRFRZ, RIUE', max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
