# Generated by Django 5.2.7 on 2025-11-17 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_remove_perfilusuario_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesis',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Frec. Cardíaca (lpm)'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Frec. Respiratoria (rpm)'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=20, verbose_name='Presión Arterial'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='rut_paciente',
            field=models.CharField(blank=True, help_text='Ej: 12.345.678-9', max_length=12, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(45)], verbose_name='Temperatura (°C)'),
        ),
    ]
